version: '3.8'

services:
  db:
    image: mysql:8.0
    # O server-id é extraído do último número do IP para ser único
    command: --server-id=${ID_NODO} --log-bin=mysql-bin --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ddb_distributed
    volumes:
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "3306:3306"
    networks:
      - ddb_net

  node:
    build: .
    container_name: ddb_node
    depends_on:
      - db
    environment:
      - MY_IP=${MY_IP}
      - ALL_NODES=${ALL_NODES}
      - DB_URL=jdbc:mysql://db:3306/ddb_distributed?allowMultiQueries=true
      - DISPLAY=${DISPLAY}
    ports:
      - "5000:5000"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # Mapeamento para interface gráfica
    networks:
      - ddb_net

networks:
  ddb_net:
    driver: bridge